Update dynamic_layers.py
MiXIL/soilscape_upscaling pull request #1
Opened 2017-11-18 22:23 UTC by jbwhitco

Changed line 209 to have the variable 'elements' formed based on just the basename of the UAVSAR file, such that element[1] is always the date string of the UAVSAR file.

2017-11-18 23:03 UTC, jbwhitco commented
Hopefully this pull request includes the following two changes:
1) Minor bug correction on line 209 of dynamic layers.py.
2) Replace upscaling_utilities.py with a python-only (i.e., no xml) version.

2017-11-19 08:11 UTC, danclewley requested changes
Thanks for the updates. I've made some minor changes it would be good to make before merging. As some stage I'll try and update so it doesn't require creating 11 new images before colouring.

2017-11-19 08:11 UTC, danclewley commented on soilscape_upscaling/upscaling_utilities.py
> -This file is licensed under the GPL v3 Licence. A copy of this
Need to keep licence text in header.

2017-11-19 08:11 UTC, danclewley commented on soilscape_upscaling/upscaling_utilities.py
> +def colour_SM_image(inimage, colorimage, max_value=0.5, band=1):
Would be better to use the English spelling `colourimage` for consistency.

2017-11-19 08:11 UTC, danclewley commented on soilscape_upscaling/upscaling_utilities.py
> +            os.system('rm '+color[i])
Better to use `os.remove` here, should also work under Windows. Alternatively could use a temp directory (`tempfile.mkdtemp`) for the individual colour bands and remove the entire thing using `shutil.rmtree` which would also take care of any  .aux.xml ancillary files.

2017-11-20 08:02 UTC, jbwhitco commented
Corrected header text and variable names and streamlined removal of temporary files.

2017-11-22 20:01 UTC, merged